services:
  redis:
    image: redis:7.0.8
    container_name: redis
    networks:
      - redis
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./config:/usr/local/etc/redis
    ports:
      - "127.0.0.1:6379:6379"
    command: ["redis-server", "--requirepass 12345678"]

networks:
  redis:
    attachable: true
    name: "redis"
    external: false