name: application

services:
  fedora:
    image: fedora:42
    container_name: fedora
    hostname: fedora
    tty: true
    networks:
      - "linux"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G