name: dns

services:
  smartdns:
    image: "pymumu/smartdns:Release47.1"
    container_name: "smartdns"
    ports:
      - "6053:53/udp"
      - "6053:53/tcp"
      - "6080:6080"
    volumes:
      - "./config:/etc/smartdns"
      - "./data:/var/lib/smartdns"
    restart: unless-stopped