name: application

services:
  alpine:
    image: alpine:3.20.3
    container_name: alpine
    hostname: alpine
    tty: true
    expose:
      - 5900
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"
