name: application

services:
  arch:
    image: archlinux:multilib-devel
    container_name: arch
    hostname: arch
    tty: true
    expose:
      - 5900
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"
