include:
  - ../commons/docker-compose-application-include.yaml

services:
  qbittorrent:
    image: "ghcr.io/linuxserver/qbittorrent:5.1.4"
    container_name: "qbittorrent"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "WEBUI_PORT=${WEBUI_PORT}"
      - "TORRENTING_PORT=${TORRENTING_PORT}"
      - "TZ=Asia/Shanghai"
    restart: unless-stopped
    volumes:
      - "qbittorrent:/downloads"
      - "./config:/config"
    ports:
      - "${WEBUI_PORT}:${WEBUI_PORT}"
      - "${TORRENTING_PORT}:${TORRENTING_PORT}"
      - "${TORRENTING_PORT}:${TORRENTING_PORT}/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"