name: proxy

services:
  sing-box:
    image: "ghcr.io/sagernet/sing-box:v1.12.10"
    container_name: "sing-box"
    ports:
      - "9090:9090"
      - "7890:7890"
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.lo.accept_local=1
    cap_add:
      - NET_ADMIN
      - BPF
      - PERFMON
    privileged: true
    volumes:
      - "${LANDSCAPE_CONFIG_DIR}/unix_link/:/ld_unix_link/:ro"
      - "./app:/app"
    entrypoint: [ "/app/start.sh" ]
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"