name: proxy

services:
  sing-box:
    build:
      dockerfile: Dockerfile
      args:
        REDIRECT_PKG_HANDLER_VERSION: v0.12.2
        SING_BOX_VERSION: v1.12.20
    container_name: "sing-box"
    ports:
      - "9090:9090"
      - "7890:7890"
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.lo.accept_local=1
      - net.ipv6.conf.lo.accept_local=1
    cap_add:
      - NET_ADMIN
      - BPF
      - PERFMON
    privileged: true
    volumes:
      - "${LANDSCAPE_CONFIG_DIR}/unix_link/:/ld_unix_link/:ro"
      - "./app/server/sing-box:/app/server/sing-box"
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"