name: application

services:
  dm:
    image: greyhawk/dm8_single:dm8_20241022_rev244896_x86_rh6_64
    container_name: dm
    restart: unless-stopped
    volumes:
      - "./data:/opt/dmdbms/data"
    ports:
      - "127.0.0.1:5236:5236"
    networks:
      - dm
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"