services:
  dae:
    image: "daeuniverse/dae:20250824"
    volumes:
      - "/sys:/sys"
      - "./config:/etc/dae"
    container_name: "dae"
    restart: unless-stopped
    privileged: true
    network_mode: host
    pid: host
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "1"