name: application

services:
    openlist:
        image: "ghcr.io/openlistteam/openlist-git:v4.1.6-ffmpeg"
        container_name: "openlist"
        environment:
            UMASK: "${UMASK}"
            TZ: "Asia/Shanghai"
            OPENLIST_ADMIN_PASSWORD: ${OPENLIST_ADMIN_PASSWORD}
            RUN_ARIA2: false
        volumes:
            - "./data:/opt/openlist/data"
        ports:
            - "5244:5244"
        restart: unless-stopped
        user: ${UID}:${GID}